### ISSUE TITLE
Parabéns !!!!

### ISSUE THREAD

**Issue by MFerrugem** [jun1rox/trabalho-ps-calingaert#7]
Parabéns !!! Trabalho bem executado e dentro das especificações !!!!
Fiquei feliz pelos comentários finais de  vocês em relação ao desafio VENCIDO, de implementar o  conhecimento básico passado em aula e pelo trabalho em conjunto.

Boas férias !!!!

**Comment by jun1rox** [comment]
Muito obrigado, professor! Boas férias pro senhor também e um bom final de ano pra ti e tua família.
